---
name: Test salt-test-lab
on:
  workflow_run:
    workflows:
      - "Run Pre-Commit hooks"
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: "true"

jobs:
    test:
      name: Build and configure the basic salt test environment
      runs-on: ubuntu-latest
      steps:
        - name: Set up git repository
          uses: actions/checkout@v2

        - name: Install golang
          uses: actions/setup-go@v2
          with:
            go-version: '^1.17.2'

        - name: Install mage
          run: go install github.com/magefile/mage@latest

        - name: Build basic test lab
          run: mage buildBasic

        - name: Tear down basic test lab
          run: mage destroyBasic

        - name: Build extended test lab
          run: mage buildExtended

        - name: Tear down extended test lab
          run: mage destroyExtended

        - name: Setup tmate session if any part of the action fails
          if: ${{ failure() }}
          uses: mxschmitt/action-tmate@v3
